sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t pkhare/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pkhare/docker-react npm run test

